apply colours and new formatting to the post provision/up scripts

diff --git a/config/homebin/vagrant_provision b/config/homebin/vagrant_provision
--- a/config/homebin/vagrant_provision
+++ b/config/homebin/vagrant_provision
@@ -11,18 +11,21 @@
 # Look for a custom trigger file. If this exists, we'll assume that
 # all trigger actions should be handled by this custom script. If
 # it does not exist, then we'll handle some basic tasks.
+#set -eo pipefail
+source /srv/provision/provision-helpers.sh
 
-echo " ▷ Post provision script"
+vvv_success " ▷ Post provision script"
 
 if [[ -f /srv/config/homebin/vagrant_provision_custom ]]; then
-	echo " * Custom vagrant provision script found, executing vagrant_provision_custom"
+	vvv_info " * Custom vagrant provision script found, executing vagrant_provision_custom"
 	/srv/config/homebin/vagrant_provision_custom
 fi
 
-echo " * Restarting Nginx and MySQL"
+vvv_info " * Restarting Nginx"
 sudo service nginx restart
+vvv_info " * Restarting MariaDB"
 sudo service mysql restart
-echo " * Syncing clocks"
+vvv_info " * Syncing clocks"
 sudo ntpdate -u ntp.ubuntu.com
 
 RED="\033[38;5;9m"
@@ -65,6 +68,6 @@ else
 	echo -e "${RED} ⚠ The failed provisioners left these logs:"
 
 	# List failed provisioners, and pipe them through xargs to print them in a formatted way.
-	ls -A /vagrant/failed_provisioners/ | xargs -I "LOGFILE" echo -e "   - log/provisioners/${date_time}/LOGFILE.log"
+	ls -A /vagrant/failed_provisioners/ | xargs -I "LOGFILE" vvv_error "   - <b>log/provisioners/${date_time}/LOGFILE.log</b>"
 	echo -e "${RED} ──────────────────────────────────────────────────${CRESET}"
 fi
